@node Build-instructions
@section Build instructions

Make sure that Go is installed. For example to install it from packages:

@table @asis
@item FreeBSD
    @verb{|pkg install go|}
@item Debian, Ubuntu
    @verb{|apt install golang|}
@end table

@example
$ [fetch|wget] http://www.nncpgo.org/download/nncp-@value{VERSION}.tar.xz
$ [fetch|wget] http://www.nncpgo.org/download/nncp-@value{VERSION}.tar.xz.sig
$ gpg --verify nncp-@value{VERSION}.tar.xz.sig nncp-@value{VERSION}.tar.xz
$ xz --decompress --stdout nncp-@value{VERSION}.tar.xz | tar xf -
$ make -C nncp-@value{VERSION} all
@end example

There is @command{install} make-target respecting @env{DESTDIR}. It will
install binaries and info-documentation:

@example
# make -C nncp-@value{VERSION} install PREFIX=/usr/local
@end example
