@node Новости
@section Новости

@node Релиз 5.3.3
@subsection Релиз 5.3.3
@itemize

@item
Больше различных проверок в коде на ошибки.

@item
Обновлены зависимые библиотеки.

@end itemize

@node Релиз 5.3.2
@subsection Релиз 5.3.2
@itemize

@item
Исправлена некорректная логика @option{onlinedeadline} timeout-а, при
котором соединение могло не учитывать факты прихода пакетов и обрывать
связь.

@end itemize

@node Релиз 5.3.1
@subsection Релиз 5.3.1
@itemize

@item
Исправлена работоспособность @option{onlinedeadline} с адресами вызова
использующими внешние команды (@verb{#"|somecmd"#}).

@item
@command{nncp-stat} имеет опцию @option{-pkt} показывающую информацию по
каждому пакету в spool.

@end itemize

@node Релиз 5.3.0
@subsection Релиз 5.3.0
@itemize

@item
Сообщения прогресса содержат префикс, поясняющий выполняемое действие.

@item
Исправлено не происходящее дополнение (padding) handshake сообщений.

@item
Завершать все порождаемые в SP протоколе горутины, меньше утечек памяти.

@item
SP протокол порождает меньше вызовов записей (соответственно, и TCP
пакетов) в сокет.

@item
Проверять @option{onlinedeadline} и @option{maxonlinetime} ежесекундно,
независимо от чтения из сокета (раз в 10 секунд в худшем случае).

@item
Раз в минуту, если нет более никакого другого трафика, посылаются PING
пакеты в SP-соединении. Это позволит быстрее понимать что соединение
более не работоспособно.

@item
@command{nncp-toss} использует lock-file для предотвращения
одновременной обработки зашифрованных пакетов.

@end itemize

@node Релиз 5.2.1
@subsection Релиз 5.2.1
@itemize

@item
Исправлена обработка ошибки SP протокола, иногда вызывающая панику программы.

@end itemize

@node Релиз 5.2.0
@subsection Релиз 5.2.0
@itemize

@item
Большинство команд по умолчанию показывают однострочный прогресс
выполнения операции. Появились @option{-progress}, @option{-noprogress}
опции командной строки, @option{noprogress} опция конфигурационного
файла.

@item
Исправлен некорректный код возврата @command{nncp-check} команды,
который возвращал ошибку когда всё хорошо.

@item
Проверка свободного места для пакетов, во время выполнения
@command{nncp-bundle -rx}.

@end itemize

@node Релиз 5.1.2
@subsection Релиз 5.1.2
@itemize

@item
Исправлена @strong{критичная} уязвимость: аутентификация online нод
могла приводить к некорректной идентификации удалённой стороны, позволяя
скачивать чужие зашифрованные пакеты.

@item
Исправлена ошибка: в новосозданных конфигурационных файлах, приватный
публичный ключ Noise были поменяны местами, что приводило к
невозможности online аутентификации нод.

@item
Явная синхронизация (fsync) директорий для гарантированного
переименования файлов.

@end itemize

@node Релиз 5.1.1
@subsection Релиз 5.1.1
@itemize

@item
Исправлена работоспособность @command{nncp-file} с @option{-chunked 0} опцией.

@end itemize

@node Релиз 5.1.0
@subsection Релиз 5.1.0
@itemize

@item
@command{nncp-file} может отправлять директории, автоматически на лету
создавая pax архив.

@item
Во время создания исходящих сообщений проверяется наличие свободного
места на файловой системе.

@item
@option{freq}, @option{freqminsize}, @option{freqchunked} опции
конфигурационного файла заменены на структуру
@option{freq: @{path: ..., minsize: ..., chunked: ...@}}.

@item
Добавлена @option{freq.maxsize} опция конфигурационного файл,
запрещающая ответ на файловый запрос больше заданного размера.

@item
Возможность оповещения об успешно выполненных командах (exec) через
@option{notify.exec} опцию конфигурационного файла.

@end itemize

@node Релиз 5.0.0
@subsection Релиз 5.0.0
@itemize

@item
@strong{Несовместимое} изменение формата конфигурационного файла:
YAML заменён на Hjson, из-за его гораздо большей простоты, без
заметной потери функционала и удобства.

@item
@strong{Несовместимое} изменение формата простых пакетов. Работа со
старыми версиями не поддерживается. @code{zlib} сжатие заменено на
@code{Zstandard}, так как оно значительно быстрее и эффективнее, не
смотря на то, что версия библиотеки ещё не проверена временем.

@item
Возможность соединяться с удалёнными нодами не только по TCP, но и через
pipe вызов сторонней команды.

@item
@command{nncp-cfgnew} генерирует конфигурационный файл с множеством
комментариев. Можно использовать @option{-nocomments} опцию для старого
поведения.

@item
Дубликаты имён файлов имеют суффикс @file{.CTR}, вместо @file{CTR},
чтобы избежать возможных коллизий с @file{.nncp.chunkCTR}.

@item
Возможность переопределить umask процесса через опцию конфигурационного
файла.

@item
По умолчанию файлы и директории создаются с 666/777 правами доступа,
позволяя управлять ими @command{umask}-ом.

@item
Обновлены зависимости.

@item
Полное использование go модулей для управления зависимостями
(используется @code{go.cypherpunks.ru/nncp/v5} namespace).

@item
Отмена автоматического использования более новых версий GNU GPL
(лицензия проекта GNU GPLv3-только).

@end itemize

@node Релиз 4.1
@subsection Релиз 4.1
@itemize
@item Восстановлена работоспособность на GNU/Linux системах и Go версии 1.10.
@end itemize

@node Релиз 4.0
@subsection Релиз 4.0
@itemize

@item
@strong{Несовместимое} изменение формата зашифрованных и eblob пакетов:
используется AEAD режим шифрования с 128 КиБ блоками, так как раньше
@command{nncp-toss} не проверял MAC зашифрованного пакета прежде чем
отсылать дешифрованные данные внешней команде. Старые версии не
поддерживаются.

@item
Проверка доступного места перед копированием во время работы
@command{nncp-xfer}, @command{nncp-daemon}, @command{nncp-call(er)}.

@item
@command{nncp-call} имеет возможность только показывать список пакетов
на удалённой машине, без их передачи.

@item
@command{nncp-call} имеет возможность передавать только чётко указанные пакеты.

@item
Восстановлена работоспособность @option{xxrate} настройки в
@option{calls} секции конфигурационного файла.

@item
Зависимые библиотеки обновлены.

@item
Небольшие исправления ошибок.

@item
Начало использования @code{go.mod} подсистемы.

@end itemize

@node Релиз 3.4
@subsection Релиз 3.4
@itemize
@item @command{nncp-daemon} может быть запущен как @command{inetd}-служба.
@end itemize

@node Релиз 3.3
@subsection Релиз 3.3
@itemize

@item
@command{nncp-daemon}, @command{nncp-call}, @command{nncp-caller}
проверяют существование @file{.seen} файла и расценивают его как то, что
файл уже был скачан. Возможно передача данных была осуществлена
сторонним способом и удалённая сторона должна быть оповещена об этом.

@item
Если более высокоприоритетный пакет попадает в спул, то
@command{nncp-daemon} добавит его в очередь отправки первым, прерывая
низкоприоритетные передачи.

@item
К средствам связанным с online-соединениями (@command{nncp-daemon},
@command{nncp-call}, @command{nncp-caller}) добавлен простой
ограничитель скорости.

@item
Возможность задания приоритета символьными обозначениями:
@verb{|NORMAL|}, @verb{|BULK+10|}, @verb{|PRIORITY-5|}, итд.

@item
Изменены значения приоритетов по-умолчанию:
для @command{nncp-exec} с 64 на 96,
для @command{nncp-freq} с 64 на 160,
для @command{nncp-file} с 196 на 224.

@end itemize

@node Релиз 3.2
@subsection Релиз 3.2
@itemize
@item
@strong{Несовместимое} изменение формата @emph{bundle} архивов и
работоспособность @command{nncp-bundle} команды с Go 1.10+. Bundle
должен быть корректным tar архивом, но Go 1.9 делал его недействительным
из-за длинных путей внутри. NNCP нечаянно был зависим от этой баги.
Явное добавление @file{NNCP/} директории в архив восстанавливает
работоспособность с корректными tar архивами.
@end itemize

@node Релиз 3.1
@subsection Релиз 3.1
@itemize
@item
Возможность отключать пересылку через промежуточные ноды используя
@verb{|-via -|} опцию командной строки.
@end itemize

@node Релиз 3.0
@subsection Релиз 3.0
@itemize

@item
@strong{Несовместимое} изменение формата простых пакетов. Работа со
старыми версиями не поддерживается.

@item
Добавлена возможность удалённого исполнения команд, путём
конфигурирования @option{exec} опции конфигурационного файла и
использования команды @command{nncp-exec}:
    @itemize
    @item
    Команда @command{nncp-mail} заменена более гибкой и широкой
    @command{nncp-exec}. Вместо вызова @verb{|nncp-mail NODE RECIPIENT|}
    нужно использовать @verb{|nncp-exec NODE sendmail RECIPIENT|}.
    @item
    @option{sendmail} опция конфигурационного файла заменена на более гибкую
    @option{exec}. @verb{|sendmail: [...]|} нужно заменить на @verb{|exec:
    sendmail: [...]|}.
    @end itemize

@item
Возможность переопределить @option{via} опцию конфигурации для целевого
узла через @option{-via} опцию командной строки для следующих команд:
@command{nncp-file}, @command{nncp-freq}, @command{nncp-exec}.

@item
Chunked файлы, меньшего размера чем указанный chunk, отправляются просто
в виде одного файла.

@item
Exec команды вызываются с дополнительными переменными окружения
@env{NNCP_NICE} и @env{NNCP_SELF}.

@item
Отправляемые файлы в ответ на запрос имеют приоритет указанный в запросе.
Указать их желаемый приоритет во время вызова @command{nncp-freq} можно
аргументом @option{-replynice}.

@item
Команде @command{nncp-toss} можно сказать не обрабатывать определённые
типы пакетов, за счёт опций @option{-nofile}, @option{-nofreq},
@option{-noexec}, @option{-notrns}.

@item
По-умолчанию @command{nncp-file} команда для
@option{-minsize}/@option{-chunked} опций использует
@option{FreqMinSize}/@option{FreqChunked} из конфигурационного файла.
Это можно отключить указав нулевое значение.

@end itemize

@node Релиз 2.0
@subsection Релиз 2.0
@itemize

@item
@strong{Несовместимое} изменение формата зашифрованных и eblob пакетов.
Работа со старыми версиями не поддерживается.

@item
Алгоритм шифрования Twofish заменён на ChaCha20. Он намного быстрее.
Одним криптографическим примитивом меньше.

@item
HKDF-BLAKE2b-256 KDF алгоритм заменён на BLAKE2Xb XOF. Ещё одним
криптографическим примитивом меньше (предполагая, что BLAKE2X
практически идентичен BLAKE2).

@end itemize

@node Релиз 1.0
@subsection Релиз 1.0
@itemize

@item
@strong{Несовместимое} изменение формата зашифрованных пакетов. Работа
со старыми версиями не поддерживается.

@item
@command{nncp-bundle} команда может создавать потоки зашифрованных
пакетов или потреблять их. Это полезно когда речь идёт о stdin/stdout
методах передачи (например запись на CD-ROM без создания промежуточного
подготовленного ISO образа или работа с ленточными накопителями).

@item
@command{nncp-toss} команда может создавать @file{.seen} файлы,
предотвращая приём дублированных пакетов.

@item
В команде @command{nncp-call} разрешается иметь только одного
обработчика контрольной суммы в фоне. Это полезно когда тысячи маленьких
входящих пакетов могут создать много горутин.

@item
Возможность переопределить путь до spool директории и файла журнала
через аргумент командной строки или переменную окружения.

@item
@command{nncp-rm} команда может удалять все исходящие/входящие,
@file{.seen}, @file{.part}, @file{.lock} и временные файлы.

@end itemize

@node Релиз 0.12
@subsection Релиз 0.12
@itemize
@item Команда sendmail вызывается с @env{NNCP_SENDER} переменной окружения.
@end itemize

@node Релиз 0.11
@subsection Релиз 0.11
@itemize
@item Вывод команды @command{nncp-stat} отсортирован по имени ноды.
@end itemize

@node Релиз 0.10
@subsection Релиз 0.10
@itemize
@item
@file{DST} аргумент @command{nncp-freq} команды теперь опционален.
По-умолчанию будет подставлен последний элемент @file{SRC} пути.
@end itemize

@node Релиз 0.9
@subsection Релиз 0.9
@itemize
@item
Исправлена обработка @option{-rx}/@option{-tx} опций @command{nncp-call}
команды. Они игнорировались.
@end itemize

@node Релиз 0.8
@subsection Релиз 0.8
@itemize
@item
Небольшое исправление ошибки в команде @command{nncp-file}, где опция
@option{-minsize} для передачи без разбиения на части была в байтах, а
не KiB-ах.
@end itemize

@node Релиз 0.7
@subsection Релиз 0.7
@itemize

@item
Возможность предоставлять данные для @command{nncp-file} через
стандартный ввод, используя временный зашифрованный файл для этого.

@item
Появилась возможность передачи файлов разбитых на части, с сопутствующей
@command{nncp-reass} командой и @option{freqchunked} опцией
конфигурационного файла. Полезно для передачи больших файлов через
маленькие устройства хранения.

@item
@option{freqminsize} опция конфигурационного файла, аналогичная
@option{-minsize}.

@item
Опция @option{-force} команды @command{nncp-xfer} переименована в
@option{-mkdir} для ясности.

@item
Опция @option{-minsize} задаётся в KiB, а не байтах, для удобства.

@item
Команда @command{nncp-newcfg} переименована в @command{nncp-cfgnew},
а @command{nncp-mincfg} в @command{nncp-cfgmin}, для того чтобы они
имели общий префикс и были сгруппированы для удобства.

@item
Появилась команда @command{nncp-cfgenc}, позволяющая
шифровать/дешифровать конфигурационный файл, чтобы безопасно его хранить
без использования OpenPGP или других подобных инструментов.

@item
Обновлены зависимые криптографические библиотеки.

@end itemize

@node Релиз 0.6
@subsection Релиз 0.6
@itemize
@item Появилась небольшая команда @command{nncp-rm}.
@item Обновлены зависимые криптографические библиотеки.
@end itemize

@node Релиз 0.5
@subsection Релиз 0.5
@itemize
@item
Тривиальное небольшое исправление в значениях приоритетов по-умолчанию в
@command{nncp-file} и @command{nncp-freq} командах.
@end itemize

@node Релиз 0.4
@subsection Релиз 0.4
@itemize

@item
Небольшое исправление в @command{nncp-call}, @command{nncp-caller},
@command{nncp-daemon}: иногда они могли падать с segmentation fault
ошибкой (данные не терялись).

@item
@command{nncp-newnode} переименована в @command{nncp-newcfg} --
это короче и удобнее для использования.

@item
Появилась команда @command{nncp-mincfg}: вспомогательная утилита
позволяющая создать минималистичный урезанный конфигурационный файл без
приватных ключей, что полезно во время использования @command{nncp-xfer}.

@end itemize

@node Релиз 0.3
@subsection Релиз 0.3
@itemize
@item Исправлена совместимость с Go 1.6.
@end itemize

@node Релиз 0.2
@subsection Релиз 0.2
@itemize

@item
@strong{Несовместимое} изменение формата пакета (магическое число тоже
изменено): поле размера пакета шифруется и не посылается в открытом виде.

@item
@option{-minsize} опция даёт возможность автоматически дополнять
исходящие пакеты до указанного минимального размера.

@item
@command{nncp-daemon} и @command{nncp-call}/@command{nncp-caller} всегда
в фоне проверяют появление исходящих @emph{tx} пакетов пока подключены.
Удалённая сторона сразу же оповещается об этом.

@item
@option{-onlinedeadline} опция даёт возможность выставления timeout-а на
неактивность в online соединении, когда оно должно быть отключено. Она
может быть использована для сохранения соединения на долгое время.

@item
@option{-maxonlinetime} опция даёт возможность указания максимального
возможного времени жизни соединения.

@item
Появилась @command{nncp-caller} команда: клиент TCP-демона работающий по
cron-у.

@item
@command{nncp-pkt} команда может разжимать данные.

@end itemize
