@node Русский
@unnumbered Информация на русском

@menu
* Подробнее об утилитах NNCP: Об утилитах.
* Сравнение с существующими решениями: Сравнение.
* Сценарии использования: Сценарии.
* Новости::
@end menu

@include about.ru.texi
@include comparison.ru.texi
@include usecases.ru.texi
@include news.ru.texi
