@node Sources
@section Development source code

Development source code contains the latest version of the code. It may
be buggy. It does not contain compiled documentation and dependent
libraries source code. Because of that, it is recommended for porters
to use @ref{Tarballs, tarballs} instead.

You can obtain it by cloning @url{http://git-scm.com/, Git}
@url{https://git.cypherpunks.ru/cgit.cgi/nncp.git/log/, repository}
and fetching dependent libraries source code as git submodules:

@verbatim
% git clone git://git.cypherpunks.ru/nncp.git nncp
% cd nncp
% git checkout develop
% git submodule update --init
@end verbatim

Also there is mirror of dependent libraries for safety if their native
repositories will be unavailable (they are seldom updated):

@multitable @columnfractions .50 .50
@headitem Software/library @tab Mirror
@item @code{github.com/davecgh/go-xdr} @tab @url{git://git.cypherpunks.ru/go-xdr.git}
@item @code{github.com/dustin/go-humanize} @tab @url{git://git.cypherpunks.ru/go-humanize.git}
@item @code{github.com/flynn/noise} @tab @url{git://git.cypherpunks.ru/noise.git}
@item @code{github.com/gorhill/cronexpr} @tab @url{git://git.cypherpunks.ru/cronexpr.git}
@item @code{golang.org/x/crypto} @tab @url{git://git.cypherpunks.ru/crypto.git}
@item @code{golang.org/x/net} @tab @url{git://git.cypherpunks.ru/net.git}
@item @code{golang.org/x/sys} @tab @url{git://git.cypherpunks.ru/sys.git}
@item @code{gopkg.in/check.v1} @tab @url{git://git.cypherpunks.ru/check.git}
@item @code{gopkg.in/yaml.v2} @tab @url{git://git.cypherpunks.ru/yaml.git}
@end multitable
