@node UsecaseBroadcastRU
@subsection Односторонняя широковещательная связь

Иногда у вас есть ёмкий, но односторонний, канал связи, например
широковещательный сигнал со спутника. Вы не можете использовать online
@ref{Sync, протокол синхронизации}, потому что он требует двустороннего
взаимодействия.

Вы можете использовать, так называемые, @ref{Bundles, пачки} и потоково
отсылать их. Они -- всего-лишь последовательность @ref{Encrypted,
зашифрованных пакетов}, которые вы можете принять.

@example
$ nncp-bundle -tx alice bob eve @dots{} | команда для отправки широковещательной рассылки
$ команда для приёма широковещательной рассылки | nncp-bundle -rx
@end example

Встроенная возможность определять дубляжи пакетов позволит вам
переотправлять широковещательные рассылки время от времени, повышая
шансы на то, что получатель примет их, регулярно слушая рассылку.
