@node UsecaseCallerRU
@subsection Дешёвая ночная связь

Стоимость Интернет/телефонного трафика может варьироваться, в
зависимости от времени дня. Ночные звонки/соединения могут быть дешевле
в два раза. Вы хотите посылать ваши файлы в это время, но позволять
изредка проходить высокоприоритетной почте в любое время. А также вы
хотите проходить любому трафику когда узел доступен через ЛВС (LAN).

Вы легко можете настроить ваши предпочтения в @ref{Call, настройках
звонков} для @command{@ref{nncp-caller}} команды, используемой при
online связи.

@verbatim
neigh: {
  [...]
  some-node: {
    [...]
    addrs: {
      lan: "[fe80::be5f:f4ff:fedd:2752%igb0]:5400"
      wan: "some-node.com:5400"
    }
    calls: [
      {
        cron: "*/1 * * * *"
        addr: lan
        nice: MAX
        onlinedeadline: 3600
      }
      {
        cron: "*/10 * * * *"
        addr: wan
        nice: PRIORITY
        xx: rx
      }
      {
        cron: "*/1 0-7 * * *"
        addr: wan
        nice: BULK
        onlinedeadline: 3600
        maxonlinetime: 3600
      }
    ]
  }
}
@end verbatim
