@node UsecaseCensorRU
@subsection Обход сетевой цензуры, здоровье

Это тоже подвид плохого канала связи. Некоторые правительства склонны к
запрету @strong{любого} вида личного (приватного) общения между людьми,
разрешая только доставку развлекательного контента и доступ к популярным
социальным сетям (которые уже вовсю наводнены рекламой, локально
исполняемым @url{https://www.gnu.org/philosophy/free-sw.ru.html,
проприетарным} JavaScript кодом (для слежкой за действиями пользователя,
сбором данных), бесстыдно и бессовестно эксплуатируя базовые потребности
человека в общении).

Это их естественное желание. Но никто вас не заставляет насильно
подчиняться огромным корпорациям типа Apple, Google или Microsoft. Ваш
выбор это создавать изолированные друг-к-другу сети с кучами безобидного
контента и приватными сообщениями. Только хищники тихо наблюдают за
своими жертвами в мире млекопитающих -- слежка и чувство что вы жертва,
сделавшая что-то плохое, вредит вашему здоровью.
