@node UsecaseMailRU
@subsection Доступность почтового сервера время от времени

Представьте, что у вас есть собственный @url{http://www.postfix.org/,
Postfix}/@url{http://www.exim.org/, Exim} SMTP сервер подключённый к
Интернету. Но вы читаете и пишете почтовые сообщения на своём ноутбуке,
который подключается к нему лишь время от времени. Как опустошить
очередь из ожидающих сообщений когда ноутбук подключён?

Одна из возможностей это войти на сервер и сделать что-то типа
@command{postqueue -f}, но по умолчанию у вас есть только несколько дней
на это, плюс отправитель будет получать уведомления о том, что его
сообщение всё ещё не доставлено. Кроме того, вы должны использовать
безопасный канал связи (SSH, VPN, итд).

Другая возможность это использовать POP3/IMAP4 сервер, но это слишком
переусложнённо и громоздко для такой простой задачи. Не вариант.
@url{https://ru.wikipedia.org/wiki/KISS_(%D0%BF%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF),
KISS}!

Просто скажите вашим обоим Postfix/Exim-ам (на сервере и ноутбуке)
отправлять сообщения через NNCP (@command{@ref{nncp-exec}}) на заданный узел.
Более подробно читайте для Postfix @ref{Postfix, здесь}, а для Exim
@ref{Exim, здесь}. Вся почта будет сохранятся в NNCP @ref{Spool, спуле},
который после обмена данных и распаковки вызовет локальный
@command{sendmail} для доставки почты, как-будто это произошло на этой
же машине.
