@node UsecasePOPRU
@subsection Легковесная и быстрая замена POP3/IMAP4

@command{@ref{nncp-daemon}} может быть соединён с
@command{@ref{nncp-caller}} длительное время -- он создаёт TCP
соединение на многие часы. Когда SMTP сервер получает письмо, то
вызывает @command{@ref{nncp-exec}} для создания исходящего
зашифрованного пакета. Демон ежесекундно проверяет исходящую директорию
и сразу же посылает оповещение о недоставленных пакетах противоположной
стороне, которая сразу же их может скачать.

Всего несколько дюжин байт оповещают о входящих пакетах, дюжины байт
начинающие доставку этих пакетов. Почтовые пакеты сжимаются (POP3 и
IMAP4, как правило, нет). У вас легковесный, сжатый, надёжный канал
связи с низкими задержками для почты, с сильным шифрованием и
двусторонней аутентификацией!
