@node UsecaseQoSRU
@subsection Медленная/дорогая связь для больших объёмов данных, плохой QoS

Представьте, что относительно дешёвый 2 TiB переносной жёсткий диск вы
отдаёте кому-нибудь утром каждый день (и забираете назад вечером). Это
равносильно 185 мегабитному качественному однонаправленному каналу
связи. Как насчёт большего количества и бОльших жёстких дисков? Этот
метод обмена данными называется
@url{https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%BE%D0%BF%D0%BF%D0%B8%D0%BD%D0%B5%D1%82,
флоппинет}.

NNCP поддерживает @ref{Niceness, приоритезацию трафика}: каждый пакет
имеет уровень "приятности", который гарантирует что он будет обработан
раньше или позднее остальных. Почти все команды имеют соответствующую
опцию:

@example
$ nncp-file -nice FLASH myfile node:dst
$ nncp-xfer -nice PRIORITY /mnt/shared
$ nncp-call -nice NORMAL bob
[@dots{}]
@end example

Огромные файлы могут быть разбиты на маленькие @ref{Chunked, части},
давая возможность передачи, по сути, любых объёмов используя накопители
небольших размеров.

Вы также можете использовать CD-ROM и ленточные накопители:

@example
$ nncp-bundle -tx bob | cdrecord -tao -
$ nncp-bundle -tx bob | dd of=/dev/sa0 bs=10240
@end example
