@node UsecaseUnreliableRU
@subsection Ненадёжный/дорогой канал связи

Представьте, что у вас медленный модем/радио/спутниковый канал связи,
который часто обрывается и вызывает timeout у TCP. Не все HTTP серверы
поддерживают возобновляемые скачивания. SMTP вообще не поддерживает
продолжение оборванного приёма и тяжёлые сообщения становится очень
проблематично получить. Более того, каждый обрыв может приводить к
отсылке данных с самого начала, что не всегда по карману.

Просто отправьте вашу @ref{nncp-exec, почту} и @ref{nncp-file, файлы}
через NNCP. Вы сможете использовать или offline методы доставки --
читайте о них в следующем разделе, либо использовать поставляемый NNCP
@ref{nncp-daemon, TCP демон}.

Команды:

@example
$ nncp-file file_i_want_to_send bob:
$ nncp-file another_file bob:movie.avi
@end example

добавят в очередь отправки два файла для узла @emph{bob}.
Выстрелил-и-забыл! Теперь это работа демона (или offline передачи)
доставить частями эти файлы до удалённой системы когда она будет
доступна.
