Document: nncp
Title: Debian nncp Manual
Author: <insert document author here>
Abstract: This manual describes what nncp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nncp/nncp.sgml.gz

Format: postscript
Files: /usr/share/doc/nncp/nncp.ps.gz

Format: text
Files: /usr/share/doc/nncp/nncp.text.gz

Format: HTML
Index: /usr/share/doc/nncp/html/index.html
Files: /usr/share/doc/nncp/html/*.html
