@node Use cases
@cindex use cases
@unnumbered Use cases

See also this page @ref{Сценарии, on russian}.

@menu
* Occasional connection to mail server: UsecaseMail
* Lightweight fast POP3/IMAP4 replacement: UsecasePOP
* Unreliable/expensive communication link: UsecaseUnreliable
* Slow/expensive link for high-volume data, bad QoS: UsecaseQoS
* Extreme terrestrial environments, no link: UsecaseNoLink
* One-way broadcasting communications: UsecaseBroadcast
* Satellite links: UsecaseSatelliteLinks
* Private, isolated MitM/Sybil-resistant networks: UsecaseF2F
* Highly secure isolated air-gap computers: UsecaseAirgap
* Network censorship bypassing, health: UsecaseCensor
* Reconnaissance, spying, intelligence, covert agents: UsecaseSpy
* Cheap night transfers: UsecaseCaller
* Multicast flooding transmission: UsecaseMulticast
@end menu

@include usecases/mail.texi
@include usecases/pop.texi
@include usecases/unreliable.texi
@include usecases/qos.texi
@include usecases/nolink.texi
@include usecases/broadcast.texi
@include usecases/satellite.texi
@include usecases/f2f.texi
@include usecases/airgap.texi
@include usecases/censor.texi
@include usecases/spy.texi
@include usecases/caller.texi
@include usecases/multicast.texi
